services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # on ne peut pas voir ni dechiffrer les donnees dans le volume

  app:
    build: .
    container_name: my-node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase

volumes:
  mongo-data: